# Change these first
owner: wookingwoo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: wookingwoo.com
    url: https://wookingwoo.com
  - name: jjambot-website
    url: https://jjambot.wookingwoo.com
  - name: smartwork
    url: https://smartwork.wookingwoo.com
  - name: maptool
    url: https://maptool.wookingwoo.com
  - name: wookingwoo-message
    url: https://msg.wookingwoo.com
  - name: animalface
    url: https://animalface.wookingwoo.com
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wookingwoo.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: wookingwoo-status
  introTitle: "The monitoring system for **wookingwoo**."
  introMessage: This is a status page for **wookingwoo**. [GitHub](https://github.com/wookingwoo) [wookingwoo-website](https://wookingwoo.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: wookingwoo
      href: https://wookingwoo.com
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
