# Change these first
owner: wookingwoo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: wookingwoo.com
    url: https://wookingwoo.com
  - name: jjambot-website
    url: https://jjambot.wookingwoo.com
  - name: smartwork
    url: https://smartwork.wookingwoo.com
  - name: maptool
    url: https://maptool.wookingwoo.com
  - name: message
    url: https://msg.wookingwoo.com/oauth2/login?message=%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%B4%20%ED%95%84%EC%9A%94%ED%95%A9%EB%8B%88%EB%8B%A4&returnUrl=http%3A%2F%2Fmsg.wookingwoo.com%2Fdashboard
  - name: animalface
    url: https://animalface.wookingwoo.com
  - name: wkw.one
    url: https://wkw.one
  - name: woj
    url: http://woj.wookingwoo.com/
  - name: pi
    url: https://pi.wookingwoo.com/
  - name: ip
    url: http://ip.wookingwoo.com/
  - name: namsigdang-chatbot
    method: $NAMSIGDANG_CHATBOT_SECRET_METHOD
    url: $NAMSIGDANG_CHATBOT_SECRET_URL
    headers:
      - 'Content-Type: $NAMSIGDANG_CHATBOT_SECRET_CONTENTTYPE'
    body: '$NAMSIGDANG_CHATBOT_SECRET_BODY'
    expectedStatusCodes:
      - 200
      - 400
  - name: busition
    url: https://www.busition.com/
  - name: pinecone
    url: https://pinecone.ronny.dev/
  - name: trip
    url: https://trip.ronny.dev/
  - name: trainmate
    url: https://trainmate.ronny.dev/
  - name: blockchain-simulator
    url: https://blockchain.ronny.dev/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wookingwoo.com
  # baseUrl: /your-repo-name
  logoUrl: https://wookingwoo-logo.s3.ap-northeast-2.amazonaws.com/wookingwoo_logo_img/fulllogo_horizon_fullcolor.png
  favicon: https://wookingwoo-logo.s3.ap-northeast-2.amazonaws.com/wookingwoo_logo_img/crown_fullcolor_%404x.png
  name: wookingwoo-status
  introTitle: "The monitoring system for **wookingwoo**."
  introMessage: This is a status page for **wookingwoo**. [GitHub](https://github.com/wookingwoo) [wookingwoo-website](https://wookingwoo.com)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: wookingwoo
      href: https://wookingwoo.com
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
